- name: "installing apache"
  hosts: "webserver"
  become: yes

  tasks:
    - name: install apache2
      apt:
       name: apache2
       state: latest
       update_cache: yes
      become: yes
    - name: enable apache2     
      systemd:
       name: apache2
       state: started
       enabled: yes
    - name: copy file
      copy:
       src: /var/lib/jenkins/test.sh
       dest: /home/ubuntu/test.sh
       mode: '0755'
        
   

 

